#!/bin/bash
# generate-timeline.sh — Assembles the final self-contained HTML output directory.
# Copies vendored TimelineJS3 assets, template, and timeline data into output dir.
#
# Usage: generate-timeline.sh <timeline-data.json> <output-dir> <plugin-root>
#
# Arguments:
#   $1 - Path to timeline-data.json (generated by narrative-synthesizer)
#   $2 - Output directory path (will be created if needed)
#   $3 - Plugin root directory (contains templates/ and node_modules/)

set -euo pipefail

TIMELINE_DATA="${1:?Usage: generate-timeline.sh <timeline-data.json> <output-dir> <plugin-root>}"
OUTPUT_DIR="${2:?Usage: generate-timeline.sh <timeline-data.json> <output-dir> <plugin-root>}"
PLUGIN_ROOT="${3:?Usage: generate-timeline.sh <timeline-data.json> <output-dir> <plugin-root>}"

TIMELINEJS_DIR="$PLUGIN_ROOT/node_modules/@knight-lab/timelinejs/dist"

# Verify inputs exist
if [ ! -f "$TIMELINE_DATA" ]; then
    echo "Error: Timeline data not found: $TIMELINE_DATA" >&2
    exit 1
fi

if [ ! -d "$TIMELINEJS_DIR" ]; then
    echo "Error: TimelineJS3 dist not found: $TIMELINEJS_DIR" >&2
    echo "Run 'npm install' in $PLUGIN_ROOT first." >&2
    exit 1
fi

# Verify timeline data is valid JSON
if ! jq '.' "$TIMELINE_DATA" > /dev/null 2>&1; then
    echo "Error: Invalid JSON in $TIMELINE_DATA" >&2
    exit 1
fi

# Create output directory structure
mkdir -p "$OUTPUT_DIR/assets/js"
mkdir -p "$OUTPUT_DIR/assets/css/icons"
mkdir -p "$OUTPUT_DIR/assets/css/fonts"

# Copy TimelineJS3 assets
cp "$TIMELINEJS_DIR/js/timeline.js" "$OUTPUT_DIR/assets/js/timeline.min.js"
cp "$TIMELINEJS_DIR/css/timeline.css" "$OUTPUT_DIR/assets/css/timeline.css"

# Copy icon fonts (required for navigation icons)
cp "$TIMELINEJS_DIR/css/icons/"* "$OUTPUT_DIR/assets/css/icons/" 2>/dev/null || true

# Copy default font CSS
cp "$TIMELINEJS_DIR/css/fonts/font.default.css" "$OUTPUT_DIR/assets/css/fonts/" 2>/dev/null || true

# Copy timeline data
cp "$TIMELINE_DATA" "$OUTPUT_DIR/timeline-data.json"

# Copy HTML template
cp "$PLUGIN_ROOT/templates/timeline.html" "$OUTPUT_DIR/index.html"

echo "Timeline generated at: $OUTPUT_DIR"
echo "Open $OUTPUT_DIR/index.html in a browser to view."
